version: "3"

services:
    anomalydetector:
        image: teaprj/anomaly_detector:0.42
        ports:
            - "5001:5000"
        command: "-uri ${URI} -username ${USERNAME} -base_uri ${BASE_URI} -bucket ${BUCKET} -org ${ORG} -token ${TOKEN} -url ${INFLUX_URL}"
    influxdb:
        image: influxdb:2.1.1
        volumes:
            - $PWD/data:/var/lib/influxdb2
        environment:
            DOCKER_INFLUXDB_INIT_MODE: setup
            DOCKER_INFLUXDB_INIT_USERNAME: admin
            DOCKER_INFLUXDB_INIT_PASSWORD: influxdb
            DOCKER_INFLUXDB_INIT_ORG: ${ORG}
            DOCKER_INFLUXDB_INIT_BUCKET: ${BUCKET}
            DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${TOKEN}
        ports:
            - "8086:8086"

    telegraf:
        image: library/telegraf:1.21.2
        hostname: telegraf
        container_name: telegraf
        volumes:
            - ./telegraf:/etc/telegraf
            - /var/run/docker.sock:/var/run/docker.sock