version: "3"

services:
    anomalydetector:
        image: teaprj/anomaly_detector:0.42
        ports:
            - "5001:5000"
        command: "-uri ${URI} -username ${USERNAME} -base_uri ${BASE_URI} -bucket ${BUCKET} -org ${ORG} -token ${TOKEN} -url ${INFLUX_URL}"